### ISSUE TITLE
Support Lazy routing

### ISSUE THREAD

**Issue by elivibe** [arlac77/svelte-guard-history-router#3009]
hi  @arlac77 

When running the example, it was found that the routing is not dynamically loaded.I couldn't find the lazy loading syntax for loading routes/components lazily. Does this feature exist?

![image](https://github.com/user-attachments/assets/59944c5c-dec7-49ef-8ca1-99ba8b0c91e6)

**Comment by arlac77** [comment]
Hello,
currently You can only add single routes

```js
  const route = { path: '...', component: ...};
  router.addRoute(route)
```

and they will stay attached to the router forever.
